project_id = "rfkfjfvlcushtejkgbmg"

[auth]
jwt_expiry = 2592000
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10

[functions.recognize-product]
verify_jwt = true

[functions.recognize-product-by-photo]
verify_jwt = true

[functions.cleanup-temporary-photos]
verify_jwt = false

[functions.bulk-import-products]
verify_jwt = true

[functions.recognize-expiry-date]
verify_jwt = true

[functions.scan-product-photos]
verify_jwt = true

[functions.upload-to-imagekit]
verify_jwt = false

[functions.login-by-username]
verify_jwt = false

[functions.setup-external-db]
verify_jwt = false

[functions.transfer-queue-to-products]
verify_jwt = true
